### ISSUE TITLE
installation help

### ISSUE THREAD

**Issue by sfahadshahzad** [MagmaPlayout/mp-core#1]
is there any wiki available to build or test.

Fahad

**Comment by Rombusevil** [comment]
Hello Fahad, this project is in development.
We're still working on the first prototype of a project that will be called "Magma Playout", this is the core app of that.
In a couple of days I'll commit the needed libraries for this to build, but as I said earlier there's no much to do with this yet :)

**Comment by sfahadshahzad** [comment]
Hello,

Is there any update regarding project Maga Playout.

Fahad :)

**Comment by Rombusevil** [comment]
Hello @sfahadshahzad , I've added a spanish installation manual here: [https://github.com/MagmaPlayout/mp-installer/blob/master/docs/installation-manual/manual_instalacion.md](https://github.com/MagmaPlayout/mp-installer/blob/master/docs/installation-manual/manual_instalacion.md) I'll add an english version in the next couple of weeks. Still debugging the installation script.
One thing to note is that all our changes are still on "devel" branches, the installer checks out the master branches, so an aditional step of running `mp-installer/devel/updateAllRepos.sh`should be issued (at the end).
